# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui-design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtCore import QTimer, Qt
import cv2
from ultralytics import YOLO
import numpy as np
from modul import point_proc, wheremypoint, far, camera_position 


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 493)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"background-color: rgb(255, 242, 221);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.mode_combo = QtWidgets.QComboBox(self.centralwidget)
        self.mode_combo.setGeometry(QtCore.QRect(10, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.mode_combo.setFont(font)
        self.mode_combo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mode_combo.setObjectName("mode_combo")
        self.mode_combo.addItem("")
        self.mode_combo.addItem("")
      
        self.upload_btn = QtWidgets.QPushButton(self.centralwidget)
        self.upload_btn.setGeometry(QtCore.QRect(460, 420, 131, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.upload_btn.setFont(font)
        self.upload_btn.setToolTip("")
        self.upload_btn.setAutoFillBackground(False)
        self.upload_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.upload_btn.setInputMethodHints(QtCore.Qt.ImhNone)
        self.upload_btn.setObjectName("upload_btn")
        self.upload_btn.setVisible(False)
        
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(10, 100, 411, 351))
        self.image_label.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.image_label.setText("")
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.image_label.setVisible(False)
        
        self.coord_input = QtWidgets.QLineEdit(self.centralwidget)
        self.coord_input.setGeometry(QtCore.QRect(460, 100, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.coord_input.setFont(font)
        self.coord_input.setStyleSheet("background-color: rgb(255, 219, 183);\n"
"background-color: rgb(255, 255, 255);")
        self.coord_input.setObjectName("coord_input")
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(460, 140, 251, 271))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(115, 115, 115);\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")       
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
               

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Выберите источник "))
        self.mode_combo.setItemText(0, _translate("MainWindow", "Изображение"))
        self.mode_combo.setItemText(1, _translate("MainWindow", "Видео"))
        self.upload_btn.setText(_translate("MainWindow", "Добавить фото"))
        self.coord_input.setPlaceholderText(_translate("MainWindow", "Введите координаты (x,y)"))
        self.label_3.setText(_translate("MainWindow", "Результат поиска пути"))
